### PR TITLE
Nvme support

### PR DESCRIPTION
**Pull request by stemid**
This is a first draft for simple nvme support, where the --json argument is available for smartctl.

What do you think? What improvements do you want to see before merging?

### CODE REVIEW

**Comment by matusnovak** [comment]
Hold up, there was `--json` available for smartctl the whole time? How did I miss this... 

This looks very well done! Thank you. I will give it a test on one of my NVMe drive later this week and will report back to you.

**Comment by stemid** [comment]
@matusnovak thanks. I sort of suspected that when you saw the json argument you'd want to re-write everything. ;)

**Comment by matusnovak** [comment]
I have tested it and works great. Thank you very much. Sorry for the delay.

**Comment by matusnovak** [comment]
Just a note, the Docker image has been built and pushed to Docker Hub ([link](https://hub.docker.com/repository/docker/matusnovak/prometheus-smartctl)) with tag `1.2.0` and also as `latest`

**Pull request merged**
